#!/usr/bin/env bash
# Installs Nginx with special configurations
# Includes a custom 404 (page not found) containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.htm
sudo chmod 666 index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
sudo chmod 666 /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
sudo chmod 666 /etc/nginx/sites-available/default
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
