#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers using a roundrobin
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

server_config=\
"
frontend  mihdar-frontend
        bind *:80
        mode http
        default_backend mihdar-backend
backend mihdar-backend
        balance roundrobin
        server 190626-web-01 100.25.30.175:80 check
        server 190626-web-02 100.26.229.181:80 check
"
echo "$server_config" | sudo tee  /etc/haproxy/haproxy.cfg

sudo service haproxy restart
