#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers using a roundrobin
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  mihdar-frontend
        bind :80
        mode http
        default_backend mihdar-backend
backend mihdar-backend
        balance roundrobin
        server 190626-web-01 100.25.30.175:80 check
        server 190626-web-02 100.26.229.181:80 check
"
echo "$server_config" | sudo tee  /etc/haproxy/haproxy.cfg
haproxy_config=\
"# Defaults file for HAProxy
#
# This is sourced by both, the initscript and the systemd unit file, so do not
# treat it as a shell script fragment.

# Change the config file location if needed
#CONFIG="/etc/haproxy/haproxy.cfg"

# Add extra flags here, see haproxy(1) for a few options
#EXTRAOPTS='-de -m 16'
ENABLED=1
"

# enable haproxy => started by init script
echo "$haproxy_config" | sudo tee  /etc/haproxy/haproxy.cfg
sudo service haproxy restart
