#!/usr/bin/env bash
# displays Best School 10 times, add Hi in 9th iteration.
i=1
while [ $i -le 10 ]
do
	if [ $i = 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
