#!/usr/bin/env bash
# displays Best School 10 times, add Hi in 9th iteration.
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	else 
		if [ $i = 8 ]
		then

			echo "good luck"
			else
			echo "Best School"
		fi
	fi
	i=$((i+1))
done
