#!/usr/bin/env bash
# Run Nginx as the nginx user listening on port 8080.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sudo echo "

server {
        listen 8080 default_server;
        location /hbnb_static { alias /data/web_static/current/;}
        listen [::]:8080 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By $hostname;
        location /redirect_me {
        return 301 http://google.com/;
        }
        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
}" | tee /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx => kill its process
pkill apache2
# start the nginx as 'nginx' user
sudo -u nginx service nginx start
